/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Certificate;

/**
 *
 * @author abramehab
 */
public class CertificateDetails extends javax.swing.JPanel {
    private Certificate cert;
    private ViewCertificate dash;

    public CertificateDetails(Certificate cert,ViewCertificate dash) {
        this.cert = cert;
        this.dash = dash;
        initComponents();

        // Set label values
        lblId.setText("Certificate ID: " + cert.getCertificateId());
        lblCourse.setText("Course: " + cert.getCourseName());
        lblDate.setText("Issue Date: " + cert.getIssueDate());
        lblStudent.setText("Student Name: " + cert.getStudent());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();

        lblId.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblId.setText("Certificate ID:");

        lblCourse.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblCourse.setText("Course Name:");

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblDate.setText("Issue Date:");

        lblStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblStudent.setText("Student Name: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStudent)
                    .addComponent(lblDate)
                    .addComponent(lblCourse)
                    .addComponent(lblId))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblId)
                .addGap(47, 47, 47)
                .addComponent(lblCourse)
                .addGap(45, 45, 45)
                .addComponent(lblDate)
                .addGap(35, 35, 35)
                .addComponent(lblStudent)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblStudent;
    // End of variables declaration//GEN-END:variables
}
