/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Certificate;
import javax.swing.SwingUtilities;

/**
 *
 * @author abramehab
 */
public class CertificateDetails extends javax.swing.JPanel {
    private Certificate cert;
    private ViewCertificate dash;

    public CertificateDetails(Certificate cert,ViewCertificate dash) {
        this.cert = cert;
        this.dash = dash;
        initComponents();

        // Set label values
        lblId.setText("Certificate ID: " + cert.getCertificateId());
        lblCourse.setText("Course: " + cert.getCourseName());
        lblDate.setText("Issue Date: " + cert.getIssueDate());
        lblStudent.setText("Student Name: " + cert.getStudent());
    }
    
    private String createCertificateText() {
        
    StringBuilder sb = new StringBuilder();
    
    
    sb.append("=============================================\n");
    sb.append("            CERTIFICATE OF COMPLETION        \n");
    sb.append("=============================================\n\n");
    
    sb.append("This certifies that\n\n");
    sb.append("    ").append(cert.getStudent()).append("\n\n");
    sb.append("has successfully completed the course\n\n");
    sb.append("    \"").append(cert.getCourseName()).append("\"\n\n");
    sb.append("Certificate ID: ").append(cert.getCertificateId()).append("\n");
    sb.append("Course ID: ").append(cert.getCourseId()).append("\n");
    sb.append("Issue Date: ").append(cert.getIssueDate()).append("\n\n");
    
    sb.append("=============================================\n");
    sb.append("Congratulations on your achievement!\n");
    sb.append("=============================================\n");
    
    return sb.toString();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        lblId.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblId.setText("....");

        lblCourse.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblCourse.setText("....");

        lblDate.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblDate.setText("....");

        lblStudent.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblStudent.setText("...");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText("Certificate Id:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel2.setText("Course ID:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel3.setText("Date:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel4.setText("Student Name:");

        jButton1.setText("Download as Json");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Download as pdf");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(125, 125, 125)
                .addComponent(jButton3)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent)
                    .addComponent(jLabel4))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save Certificate as JSON");
        String filename = "Certificate_" + cert.getCourseName().replaceAll(" ", "_") + ".json";
        fileChooser.setSelectedFile(new java.io.File(filename));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".json")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".json");
            }
            try (java.io.FileWriter writer = new java.io.FileWriter(fileToSave)) {
                writer.write(cert.toJSON().toString(4));
                
                javax.swing.JOptionPane.showMessageDialog(this, "Certificate saved as JSON successfully!");
                
            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving file: " + e.getMessage());
            }
        }
    
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         SwingUtilities.getWindowAncestor(this).dispose();
       dash.setVisible(true);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Save Certificate as Text");
    
    
    String filename = "Certificate_" + cert.getCourseName().replaceAll(" ", "_") + ".txt";
    fileChooser.setSelectedFile(new java.io.File(filename));

    
    int userSelection = fileChooser.showSaveDialog(this);

   
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();
        
      
        if (!fileToSave.getName().toLowerCase().endsWith(".txt")) {
            fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".txt");
        }
        
      
        try {
            String textContent = createCertificateText();
            
          
            try (java.io.FileWriter writer = new java.io.FileWriter(fileToSave)) {
                writer.write(textContent);
            }
            
           
            javax.swing.JOptionPane.showMessageDialog(this, "Certificate saved as text file successfully!");
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }                                        
     

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblStudent;
    // End of variables declaration                   
}
