/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author abramehab
 */
public class ChartPanel extends javax.swing.JPanel {
    private Course currentCourse;
    /**
     * Creates new form ChartPanel
     */
    public ChartPanel(Course currentcourse) {
        initComponents();
        this.currentCourse = currentcourse;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        int high = currentCourse.getStudents().size();
        int med  = high / 2;
        int low  = high / 4;

        int x = 80;  
        int barWidth = 80;

       
        g.setColor(Color.BLUE);
        g.fillRect(x, 300 - high * 5, barWidth, high * 5);
        g.setColor(Color.BLACK);
        g.drawString("High", x + 20, 320);

        x += 120;
        g.setColor(Color.MAGENTA);
        g.fillRect(x, 300 - med * 5, barWidth, med * 5);
        g.setColor(Color.BLACK);
        g.drawString("Medium", x + 10, 320);

        x += 120;
        g.setColor(Color.GRAY);
        g.fillRect(x, 300 - low * 5, barWidth, low * 5);
        g.setColor(Color.BLACK);
        g.drawString("Low", x + 20, 320);

        g.setColor(Color.BLACK);
        g.drawString("Student Statistics for " + currentCourse.getTitle(), 180, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
