package FrontEnd;


import BackEnd.Course;
import BackEnd.Instructor;
import BackEnd.InstructorService;
import BackEnd.Student;
import java.util.List;
import javax.swing.JOptionPane;
import BackEnd.JsonDatabaseManager;
import Controller.LoginController;


public class InstructorDashboard extends javax.swing.JFrame {
    private Instructor currentI;
    private LoginFrame loginFrame;
    private LoginController controller;



    /**
     * PRIMARY CONSTRUCTOR: Takes all required service objects.
     */
    public InstructorDashboard(Instructor instructor, LoginController controller,LoginFrame loginFrame) {
        initComponents();
        this.currentI = instructor;
        this.controller = controller;
        this.loginFrame=loginFrame;
    }

    public InstructorDashboard(){
    
    }

    private Course FindCourseById(String courseId){
        if(courseId==null||courseId.trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Id is empty");
            return null;
        }
        Course course = controller.getCourseById(courseId);
      if (course == null) {
            JOptionPane.showMessageDialog(this, "Error: Course not found.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        if (!course.getInstructorId().equals(currentI.getUserId())) {
            JOptionPane.showMessageDialog(this, "Error: You do not own this course.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        return course; 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Instructor Dashboard");

        jButton1.setText("Add Course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Course");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Course");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Manage Lessons");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("View Enrolled Students");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    String title = JOptionPane.showInputDialog(this, "Enter new course title:");
    if (title == null || title.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String description = JOptionPane.showInputDialog(this, "Enter course description:");
    if (description == null) {
        return; 
    }
    
    try {
        boolean success = controller.createCourse(title, description, currentI);
        if (success) {
            JOptionPane.showMessageDialog(this, "Course created successfully!");
        } else {
            JOptionPane.showMessageDialog(this, 
                "Error: Could not create course. Check console for details.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Unexpected error: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}                                        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter the Course ID to delete:");
        Course  courseToDelete=FindCourseById(courseId);
        if(courseToDelete==null){
            return;
        }
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete '" + courseToDelete.getTitle() + "'?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION
        );
        
        if (choice == JOptionPane.YES_OPTION) {
            boolean success = controller.deleteCourse(courseToDelete.getCourseId(), currentI);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Course deleted.");
            } else {
                JOptionPane.showMessageDialog(this, "Error: Course could not be deleted.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter the Course ID to edit:");
        Course courseToEdit=FindCourseById(courseId);
        if(courseToEdit==null){
            return;
        }
        String newTitle = JOptionPane.showInputDialog(this, "Enter the new title:", courseToEdit.getTitle());
    
        if (newTitle == null || newTitle.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newDescription = JOptionPane.showInputDialog(this, "Enter the new description:", courseToEdit.getDescription());
        if (newDescription == null) {
            return;
        }
    
        boolean success = controller.editCourse(courseId, newTitle, newDescription);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Course updated.");
        } else {
            JOptionPane.showMessageDialog(this, "Error: Course could not be updated.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter the Course ID to manage lessons for:");
        Course courseToManage=FindCourseById(courseId);
        if(courseToManage==null){
            return;
        }
        CourseEditorFrame editor = new CourseEditorFrame(
                controller,
                courseToManage
        );
    
        editor.setVisible(true);
        this.setVisible(false);
        editor.setDashboard(this); 
    
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter the Course ID to view students for:");
        Course courseToView =FindCourseById(courseId);
        if (courseToView == null) {
            return; 
        }
        List<Student> students = controller.getEnrolledStudents(courseToView.getCourseId());
        if (students.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No students are currently enrolled in this course.");
            return;
        }
        StringBuilder studentList = new StringBuilder("Enrolled Students for '" + courseToView.getTitle() + "':\n\n");
        for (Student student : students) {
            studentList.append("- ").append(student.getUsername()).append("\n");
        }
        JOptionPane.showMessageDialog(this, studentList.toString());

    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controller.LoginController controller = new Controller.LoginController();


                FrontEnd.LoginFrame login = new FrontEnd.LoginFrame();

                BackEnd.Instructor instructor = new BackEnd.Instructor(
                        "Test User",
                        "I100",
                        "test@app.com",
                        "hash",
                        "instructor"
                );
                new FrontEnd.InstructorDashboard(instructor, controller, login).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
