/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.Instructor;
import BackEnd.Lesson;
import Controller.LoginController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abramehab
 */
public class LessonSelectedFrame extends javax.swing.JFrame {
    private Course course;
    private LoginController controller;
    private Instructor currentinstructor;
    private LoginFrame loginFrame;



    public LessonSelectedFrame(Instructor currentinstructor, Course course, LoginController controller, LoginFrame loginFrame) {
        this.course = course;
        this.controller = controller;
        this.currentinstructor = currentinstructor;
        this.loginFrame = loginFrame;
        initComponents();
        loadLessons();
    }

    public void loadLessons(){
        DefaultTableModel tableModel = (DefaultTableModel) lessonsTable.getModel();
        tableModel.setRowCount(0);

        List<Lesson> lessons = course.getLessons();
        for (Lesson l : lessons) {
            tableModel.addRow(new Object[]{l.getLessonId(), l.getTitle()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        CreateQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Lessons in the course");

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Lesson ID", "Title"
                }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        CreateQuiz.setText("Create");
        CreateQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreateQuiz)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Back)
                                        .addComponent(CreateQuiz))
                                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>

    private void CreateQuizActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a lesson.");
            return;
        }

        Lesson selectedLesson = course.getLessons().get(selectedRow);
        if (selectedLesson.getQuiz() != null) {
            JOptionPane.showMessageDialog(this, "This lesson already has a quiz. You cannot create another one.");
            return;
        }

        CreateQuizFrame quizFrame = new CreateQuizFrame(currentinstructor, course, selectedLesson, controller, loginFrame);
        quizFrame.setVisible(true);
        this.setVisible(false);
    }


    private void BackActionPerformed(java.awt.event.ActionEvent evt) {
        InstructorDashboard dash = new InstructorDashboard(currentinstructor, controller, loginFrame);
        dash.setVisible(true);
        this.dispose();
    }




    // Variables declaration - do not modify
    private javax.swing.JButton Back;
    private javax.swing.JButton CreateQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration
}
