
package FrontEnd;


import BackEnd.Instructor;
import BackEnd.InstructorService;
import BackEnd.Student;
import BackEnd.StudentService;
import BackEnd.User;
import Controller.LoginController;

import javax.swing.JOptionPane;

/**
 *
 * @author abramehab
 */
public class LoginFrame extends javax.swing.JFrame {
    private final LoginController controller;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.controller = new LoginController(); // controller handles all backend
    }
    public LoginFrame(LoginController controller) {
        this.controller = controller;
        initComponents();
        setLocationRelativeTo(null);
    }
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setText("User name or email");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setText("Password:");

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Login, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(jPasswordField1)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Login)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
      String input = jTextField1.getText().trim(); 
    String password = new String(jPasswordField1.getPassword()).trim();

    if (input.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields");
        return;
    }


        User user = controller.login(input, password);

    if (user == null) {
        JOptionPane.showMessageDialog(this, "Invalid credentials");
        return;
    }

    JOptionPane.showMessageDialog(this, "Login successful");

   
    switch (user.getRole().toLowerCase()) {

        case "student": {
            if (!(user instanceof Student)) {
                JOptionPane.showMessageDialog(this, "User is not a student in JSON file");
                return;
            }

            Student student = controller.getStudent(user); // controller ensures it's a student
            if (student == null) {
                JOptionPane.showMessageDialog(this, "User is not a student in backend");
                return;
            }
            StudentManagement dash = new StudentManagement(student, controller);

            dash.setVisible(true);
            this.setVisible(false);
            break;
        }

        case "instructor": {
            if (!(user instanceof Instructor)) {
                JOptionPane.showMessageDialog(this, "User is not an instructor in JSON file");
                return;
            }

            Instructor instructor = controller.getInstructor(user);
            if (instructor == null) {
                JOptionPane.showMessageDialog(this, "User is not an instructor in backend");
                return;
            }
            InstructorDashboard dash = new InstructorDashboard(instructor, controller, this);

            dash.setVisible(true);
            this.setVisible(false);
            break;
        }

        default:
            JOptionPane.showMessageDialog(this, "Unknown role in JSON: " + user.getRole());
            break;
    }
    
    }//GEN-LAST:event_LoginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
