/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;

import BackEnd.Student;

import Controller.LoginController;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abramehab
 */
public class MyCourses extends javax.swing.JFrame {
    private Student currentStudent;
    private LoginController controller;
    private StudentManagement dashboard;
    /**
     * Creates new form MyCourses
     */
    public MyCourses(Student student,Controller.LoginController controller, StudentManagement dashboard) {
        initComponents();
        this.currentStudent = student;
        this.controller=controller;
        this.dashboard = dashboard;
        loadEnrolled();
    }
    private void loadEnrolled() {
        ArrayList<Course> enrolled = controller.getEnrolledCourses(currentStudent);
        DefaultTableModel model = (DefaultTableModel) myCoursesTable.getModel();
        model.setRowCount(0);
        for (Course c : enrolled) {
            model.addRow(new Object[]{c.getCourseId(), c.getTitle(), c.getDescription()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myCoursesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Viewlessons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Title ", "Describtion"
            }
        ));
        jScrollPane1.setViewportView(myCoursesTable);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Courses you are enrolled in");

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Viewlessons.setText("View lessons");
        Viewlessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewlessonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Viewlessons)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Viewlessons))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void ViewlessonsActionPerformed(java.awt.event.ActionEvent evt) {
        int sel = myCoursesTable.getSelectedRow();
        if (sel < 0) return;
        String courseId = (String) myCoursesTable.getValueAt(sel, 0);
        Course c = controller.getCourseById(courseId);
        new ViewLessons(currentStudent, controller, dashboard, c).setVisible(true);
        this.dispose();
    }                                           

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Viewlessons;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myCoursesTable;
    // End of variables declaration//GEN-END:variables
}
