/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.JsonDatabaseManager;
import BackEnd.Lesson;
import BackEnd.Student;
import BackEnd.StudentService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abramehab
 */
public class ViewLessons extends javax.swing.JFrame {
    private Student currentStudent;
    private StudentService studentService;
    private JsonDatabaseManager dbManager;
    private StudentManagement dashboard;
    private Course currentCourse;
    /**
     * Creates new form ViewLessons
     */
    public ViewLessons(Student student, StudentService studentService, JsonDatabaseManager db, StudentManagement dashboard) {
        initComponents();
        this.currentStudent = student;
        this.studentService = studentService;
        this.dbManager = db;
        this.dashboard = dashboard;
    }
    
      public ViewLessons(Student student, StudentService studentService, JsonDatabaseManager db, StudentManagement dashboard, Course course) {
        this(student, studentService, db, dashboard);
        this.currentCourse = course;
        loadLessons(course);
    }
      
       private void loadLessons(Course course) {
        DefaultTableModel model = (DefaultTableModel) lessonsTable.getModel();
        model.setRowCount(0);
        for (Lesson L : course.getLessons()) {
            boolean done = currentStudent.isLessonCompleted(course.getCourseId(), L.getLessonId());
            model.addRow(new Object[]{L.getLessonId(), L.getTitle(), done ? "Completed" : "Not completed"});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        back = new javax.swing.JButton();
        Markcompleted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Lessons included in your course");

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson ID", "Title ", "Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lessonsTable);

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Markcompleted.setText("Markcompleted ");
        Markcompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkcompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Markcompleted)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Markcompleted))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarkcompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkcompletedActionPerformed
        int sel = lessonsTable.getSelectedRow();
    if (sel < 0 || currentCourse == null) {
        JOptionPane.showMessageDialog(this, "Please select a lesson");
        return;
    }
    Lesson L = currentCourse.getLessons().get(sel);

    boolean success = studentService.markLessonCompleted(currentStudent, currentCourse, L);
    if (success) {
        JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
        loadLessons(currentCourse); 
    } else {
        JOptionPane.showMessageDialog(this, "Failed to mark lesson");
        }
    }//GEN-LAST:event_MarkcompletedActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Markcompleted;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
