/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.Lesson;
import BackEnd.Student;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abramehab
 */
public class ViewLessons extends javax.swing.JFrame {
    private Student currentStudent;
    private Controller.LoginController controller;
    private StudentManagement dashboard;
    private Course currentCourse;
    /**
     * Creates new form ViewLessons
     */
    public ViewLessons(Student student, Controller.LoginController controller, StudentManagement dashboard)
    {
        initComponents();
        this.currentStudent = student;
        this.controller = controller;
        this.dashboard = dashboard;
    }

    public ViewLessons(Student student, Controller.LoginController controller, StudentManagement dashboard, Course course) {
        this(student, controller, dashboard);
        this.currentCourse = course;
        loadLessons(course);
    }

    private void loadLessons(Course course) {
        DefaultTableModel model = (DefaultTableModel) lessonsTable.getModel();
        model.setRowCount(0);
        for (Lesson lesson : course.getLessons()) {
            boolean done = controller.isLessonCompleted(currentStudent, currentCourse, lesson);
            boolean accessible = controller.canAccessLesson(currentStudent, currentCourse, lesson);
            String status;
            if (done) {
                status = "Completed";
            } else if (!accessible) {
                status = "Locked";
            } else {
                status = "Not completed";
            }model.addRow(new Object[]{lesson.getLessonId(), lesson.getTitle(), status});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        back = new javax.swing.JButton();
        MarkCompleted = new javax.swing.JButton();
        TakeQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Lessons included in your course");

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Lesson ID", "Title ", "Content"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lessonsTable);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        MarkCompleted.setText("MarkCompleted");
        MarkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkCompletedActionPerformed(evt);
            }
        });

        TakeQuiz.setText("take quiz");
        TakeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(104, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(96, 96, 96))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(back)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TakeQuiz)
                                                .addGap(129, 129, 129)
                                                .addComponent(MarkCompleted)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(back)
                                        .addComponent(MarkCompleted)
                                        .addComponent(TakeQuiz))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarkCompletedActionPerformed(java.awt.event.ActionEvent evt) {
        int sel = lessonsTable.getSelectedRow();
        if (sel < 0 || currentCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select a lesson");
            return;
        }

        Lesson L = currentCourse.getLessons().get(sel);

        boolean success = controller.markLessonCompleted(currentStudent, currentCourse, L);
        if (success) {
            JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
            loadLessons(currentCourse);

            if (controller.isCourseCompleted(currentStudent, currentCourse)) {
                boolean certGenerated = controller.generateCertificate(currentStudent, currentCourse);
                if (certGenerated) {
                    controller.updateUser(currentStudent);
                }

                JOptionPane.showMessageDialog(this,
                        "Congratulations! You have completed the course!\n" +
                                "A certificate has been generated and added to your profile.",
                        "Course Completed",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Failed to mark lesson. Make sure you passed the quiz if required.");
        }
    }
//GEN-LAST:event_MarkCompletedActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void TakeQuizActionPerformed(java.awt.event.ActionEvent evt) {
        int sel = lessonsTable.getSelectedRow();
        if (sel < 0 || currentCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select a lesson");
            return;
        }Lesson selectedLesson = currentCourse.getLessons().get(sel);
        if (!controller.canAccessLesson(currentStudent, currentCourse, selectedLesson)) {
            JOptionPane.showMessageDialog(this, "Complete previous lessons first!");
            return;
        }
        if (selectedLesson.getQuiz() != null) {
            int used = selectedLesson.getQuiz().getAttemptsUsed(currentStudent.getUsername());
            int max = selectedLesson.getQuiz().getAttempts();
            if (used >= max) {
                JOptionPane.showMessageDialog(this,
                        "You have reached the maximum attempts (" + max + ") for this quiz!");
                return;
            }
        }

        controller.setCurrentSession(currentStudent, currentCourse, selectedLesson);
        QuizPage qp = new QuizPage(controller, this);
        qp.setVisible(true);
        dispose();
    }
//GEN-LAST:event_TakeQuizActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MarkCompleted;
    private javax.swing.JButton TakeQuiz;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
